language: java
jdk:
  - oraclejdk8

sudo: false

services:
  - docker

before_install:
  - mkdir $HOME/dependencies
  - git clone https://github.com/openvehicletracking/core.git core
  - git clone https://github.com/openvehicletracking/device-xtakip-impl.git xtakip
  - cd core && gradle clean install
  - cd ../xtakip && gradle clean install
  - cd ../openvehicletracking/collector-app

script: gradle clean build

after_success:
  - docker build -t openvehicletracking/collector .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push openvehicletracking/collector;