language: java
jdk:
  - oraclejdk8

sudo: false

services:
  - docker

before_install:
  - mkdir $HOME/dependencies
  - git clone https://github.com/openvehicletracking/core.git
  - git clone https://github.com/openvehicletracking/device-xtakip-impl.git
  - cd $HOME/dependencies/core && gradle clean install
  - cd $HOME/dependencies/device-xtakip-impl && gradle clean install
  - cd $HOME

script: gradle clean build

after_success:
  - docker build -t openvehicletracking/collector .;
    docker -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push openvehicletracking/collector;