language: java

jdk:
  - oraclejdk8

sudo: false

services:
  - docker

script: gradle clean build

after_success:
  - docker build -t openvehicletracking/collector .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push openvehicletracking/collector;
