language: java
jdk:
  - oraclejdk8

sudo: false

services:
  - docker

before_install:
  - git clone https://github.com/openvehicletracking/core.git $HOME/core
  - git clone https://github.com/openvehicletracking/device-xtakip-impl.git $HOME/xtakip
  - cd $HOME/core && gradle clean install
  - cd $HOME/xtakip && gradle clean install
  - cd $HOME/openvehicletracking/collector-app

script: gradle clean build

after_success:
  - docker build -t openvehicletracking/collector .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push openvehicletracking/collector;